services:
  db:
    image: postgres:16.3-alpine3.20
    container_name: rss-feed
    restart: always
    user: postgres
    environment:
      - POSTGRES_PASSWORD=rss-feed
      - POSTGRES_DB=blogator
    ports:
      - '5432:5432'
    volumes: 
      - db_data:/var/lib/postgresql/data

  go-app:
    build: .
    container_name: go-rss-feed
    restart: always
    depends_on:
      - db
    environment:
      - PORT=7777
      - DBCONN=postgres://postgres:rss-feed@db:5432/blogator?sslmode=disable
    ports:
      - '7777:7777'

volumes:
  db_data:
    driver: local

